# -*- coding: utf-8 -*-
"""
HMG Connect Marketing Studio — single source of truth for all products.
Add a new product = add one dict here, then re-run generate.py + export_static.py.
100% free tooling. NO AI API (deliberately — not cost effective).
"""

HMG = {
    "name": "HMG Concepts",
    "full": "His Marvellous Grace",
    "tagline": "EdTech · DataTech · FaithTech",
    "site": "https://hmgconcepts.pages.dev",
    "builder": "https://cssadewale.pages.dev",
    "wa": "https://wa.me/2348100866322",
    "waText": "+234 810 086 6322",
    "founder": "Adewale Samson Adeagbo",
    "city": "Lagos, Nigeria",
    "since": "2015",
}

PRODUCTS = [
    {
        "key": "school", "name": "School Connect", "icon": "🎓",
        "for": "Schools, colleges & training centres",
        "c1": "#0284c7", "c2": "#1e3a8a", "accent": "#fde047",
        "tagline": "Run your entire school online — admissions to report cards — for free.",
        "problem": "Still juggling registers, result sheets and fee records on paper and WhatsApp?",
        "features": [
            ("Students & Staff", "Full records with photos, classes, levels & roles."),
            ("Results & Report Cards", "Auto-computed grades, positions & printable report cards."),
            ("Fees & Payments", "Track who has paid, balances & printable receipts."),
            ("Timetable & Attendance", "Class schedules plus daily/period attendance."),
            ("CBT Online Exams", "Set & mark computer-based tests automatically."),
            ("Library, Transport & Health", "Book loans, routes and clinic records."),
            ("Parent / Guardian Portal", "Parents follow their child's results & fees."),
            ("Multi-Campus", "Switch between branches from one login."),
        ],
        "sectors": ["Nursery & Primary", "Secondary", "Colleges", "Tutorial / Lesson centres", "Skill academies"],
    },
    {
        "key": "church", "name": "Church Connect", "icon": "⛪",
        "for": "Churches, ministries & fellowships",
        "c1": "#4f46e5", "c2": "#3730a3", "accent": "#fde047",
        "tagline": "Shepherd your members, departments & finances — all in one free portal.",
        "problem": "Members' details scattered, attendance untracked, giving records in notebooks?",
        "features": [
            ("Members & Departments", "Directory, units, roles & approval workflow."),
            ("Attendance & Self check-in", "Service attendance plus member self check-in."),
            ("Giving & Finance", "Record offerings, tithes, income & expenses."),
            ("Events & Announcements", "Calendar, RSVPs & church-wide notices."),
            ("Sermons & Resources", "Share messages, notes & files."),
            ("Tasks & Polls", "Assign duties and run quick polls."),
            ("ID Cards & Gallery", "Branded member cards (QR) and photo albums."),
            ("Birthdays & Reminders", "Never miss a celebration or follow-up."),
        ],
        "sectors": ["Local assemblies", "Districts & zones", "Campus fellowships", "Cell groups", "Ministries"],
    },
    {
        "key": "business", "name": "Business Connect", "version": "v3", "icon": "💼",
        "for": "Any business sector — enterprise-grade",
        "c1": "#059669", "c2": "#065f46", "accent": "#fde047",
        "tagline": "An ERP-style platform for any business — POS, CRM, payroll & more — free.",
        "problem": "Paying monthly for software that still doesn't fit how your business runs?",
        "features": [
            ("Staff, CRM & Sales", "Team records, lead pipeline & deal tracking."),
            ("POS + Receipts + Barcode", "Fast checkout, barcode scan & printed receipts."),
            ("Online Storefront", "Public shop page; customers order online."),
            ("Invoices, Quotes & Inventory", "Branded PDFs, stock & low-stock alerts."),
            ("Payroll & Payslips", "Salary runs with printable payslips."),
            ("Finance, Expenses & Assets", "Ledgers, claims & asset register."),
            ("Analytics, Audit & Reports", "Charts, action trail & Excel/CSV export."),
            ("Free Automation Pack", "Optional Supabase functions for alerts."),
        ],
        "sectors": ["Retail & shops", "Services & agencies", "Hospitality", "Logistics & manufacturing", "Startups & NGOs"],
    },
    {
        "key": "clinic", "name": "Clinic Connect", "version": "new", "icon": "🩺",
        "for": "Clinics, hospitals, pharmacies & labs",
        "c1": "#0d9488", "c2": "#115e59", "accent": "#fde047",
        "tagline": "Patients, consultations, pharmacy & billing — a free clinic management system.",
        "problem": "Patient files lost, drug expiry missed, billing leaking revenue?",
        "features": [
            ("Patients / EMR", "Registry with MRN, demographics & allergies."),
            ("Consultations & Vitals", "Visit notes, diagnosis, BP, temp & triage."),
            ("Prescriptions", "Prescribe & print prescriptions instantly."),
            ("Lab Tests & Results", "Order tests and record results per patient."),
            ("Pharmacy / Drugs", "Stock, expiry & dispensing with alerts."),
            ("Wards / Admissions", "Admit to beds & track discharge."),
            ("Billing & Finance", "Bill consults, tests & drugs; ledgers."),
            ("Roster & Referrals", "Shift duties and in/out referrals."),
        ],
        "sectors": ["General clinics / OPD", "Hospitals", "Pharmacies", "Diagnostic labs", "Dental & maternity"],
    },
    {
        "key": "drama", "name": "DramaConnect", "icon": "🎭",
        "for": "Drama units & creative teams",
        "c1": "#003399", "c2": "#1e3a8a", "accent": "#fde047",
        "tagline": "Casting, rehearsals, attendance & finance for drama & creative units — free.",
        "problem": "Coordinating cast, rehearsals and props through endless group chats?",
        "features": [
            ("Members & Casting", "Profiles, units and role casting."),
            ("Rehearsals & Attendance", "Schedule rehearsals with self check-in."),
            ("Finance & Budgets", "Track income, expenses & production budgets."),
            ("Tasks, Polls & Inbox", "Assign duties, decide together, message."),
            ("Events & RSVP", "Productions calendar with RSVPs."),
            ("ID Cards & Gallery", "Branded cards (QR) and photo albums."),
            ("Reminders & Birthdays", "Automated nudges & celebrations."),
            ("Multi-language (EN/Yoruba)", "Use it in English or Yoruba."),
        ],
        "sectors": ["Church drama units", "School drama clubs", "Theatre groups", "Dance & choir", "Film crews"],
    },
    # ---------------- NEW products ----------------
    {
        "key": "hotel", "name": "Hotel Connect", "version": "new", "icon": "🏨",
        "for": "Hotels, lodges, resorts & guest houses",
        "c1": "#b45309", "c2": "#78350f", "accent": "#fde047",
        "tagline": "Rooms, bookings, guests, housekeeping & billing — a free hotel system.",
        "problem": "Double-booked rooms, lost reservations and reconciling cash by hand?",
        "features": [
            ("Rooms & Availability", "Room types, rates & live availability board."),
            ("Reservations & Check-in/out", "Bookings calendar with arrivals & departures."),
            ("Guest Profiles", "Guest history, IDs, preferences & contacts."),
            ("Folio & Billing", "Per-stay charges, invoices & printable receipts."),
            ("Housekeeping & Maintenance", "Room status, cleaning & repair tasks."),
            ("Restaurant / Bar POS", "Charge food & drinks to the room or pay direct."),
            ("Staff, Roster & Payroll", "Shifts, attendance & payslips."),
            ("Reports & Analytics", "Occupancy, revenue & ADR dashboards."),
        ],
        "sectors": ["Hotels", "Lodges & motels", "Resorts", "Guest houses", "Serviced apartments"],
    },
    {
        "key": "realestate", "name": "Estate Connect", "version": "new", "icon": "🏢",
        "for": "Real-estate, property & facility managers",
        "c1": "#7c3aed", "c2": "#5b21b6", "accent": "#fde047",
        "tagline": "Properties, tenants, rent & maintenance — a free property management system.",
        "problem": "Chasing rent, tracking leases and maintenance requests across spreadsheets?",
        "features": [
            ("Property & Unit Register", "Buildings, units, status & photos."),
            ("Tenants & Leases", "Lease terms, renewals & expiry alerts."),
            ("Rent & Invoices", "Rent schedules, payments & printable receipts."),
            ("Maintenance Requests", "Tenant requests with status & assignment."),
            ("Landlords & Owners", "Owner records & payout statements."),
            ("Inspections & Documents", "Reports, agreements & shared files."),
            ("Agents & Commissions", "Track listings, deals & commissions."),
            ("Finance & Analytics", "Income, arrears & occupancy dashboards."),
        ],
        "sectors": ["Estate agencies", "Landlords", "Facility managers", "Shortlet operators", "Estate associations"],
    },
    {
        "key": "gym", "name": "Gym Connect", "version": "new", "icon": "🏋️",
        "for": "Gyms, fitness studios & sports clubs",
        "c1": "#dc2626", "c2": "#991b1b", "accent": "#fde047",
        "tagline": "Members, subscriptions, check-ins & classes — a free gym management system.",
        "problem": "Members training on expired plans and no record of who showed up?",
        "features": [
            ("Members & Subscriptions", "Plans, renewals & expiry reminders."),
            ("Check-in / Attendance", "QR or front-desk check-in & visit history."),
            ("Class & Trainer Schedule", "Timetable, bookings & capacity limits."),
            ("Payments & Invoices", "Dues, point-of-sale & printable receipts."),
            ("Trainers & Roster", "Staff shifts, sessions & payroll."),
            ("Shop / Supplements POS", "Sell gear & supplements; cut stock."),
            ("Progress & Measurements", "Track member goals & body metrics."),
            ("Reports & Analytics", "Active members, revenue & churn."),
        ],
        "sectors": ["Gyms", "Fitness studios", "CrossFit boxes", "Sports clubs", "Martial-arts dojos"],
    },
    {
        "key": "logistics", "name": "Logistics Connect", "version": "new", "icon": "🚚",
        "for": "Logistics, transport & delivery companies",
        "c1": "#1d4ed8", "c2": "#1e3a8a", "accent": "#fde047",
        "tagline": "Shipments, fleet, drivers & deliveries — a free logistics management system.",
        "problem": "Parcels lost in transit, no proof of delivery and a fleet you can't track?",
        "features": [
            ("Shipments & Waybills", "Create consignments with printable waybills & tracking IDs."),
            ("Live Tracking & Status", "Move shipments from pickup to delivered with timestamps."),
            ("Fleet & Vehicles", "Vehicle register, mileage, service & documents."),
            ("Drivers & Trips", "Assign drivers, routes & trip logs."),
            ("Customers & Billing", "Senders/receivers, invoices & printable receipts."),
            ("Proof of Delivery", "Capture recipient name, signature note & time."),
            ("Maintenance & Fuel", "Log servicing, repairs & fuel spend."),
            ("Reports & Analytics", "On-time rate, revenue & fleet utilisation."),
        ],
        "sectors": ["Courier & dispatch", "Haulage & trucking", "Freight forwarders", "Last-mile delivery", "Moving companies"],
    },
    {
        "key": "salon", "name": "Salon Connect", "version": "new", "icon": "💇",
        "for": "Salons, spas & beauty studios",
        "c1": "#db2777", "c2": "#9d174d", "accent": "#fde047",
        "tagline": "Bookings, services, stylists & sales — a free salon & spa management system.",
        "problem": "Double-booked chairs, no-shows and walk-in sales you never recorded?",
        "features": [
            ("Appointments & Bookings", "Calendar by stylist with reminders & no-show notes."),
            ("Services & Price List", "Menu of services, durations & prices."),
            ("Clients & History", "Client profiles, visit history & preferences."),
            ("Stylists & Roster", "Staff schedules, commissions & payroll."),
            ("POS & Receipts", "Charge services + retail products; printable receipts."),
            ("Products / Inventory", "Retail & back-bar stock with low-stock alerts."),
            ("Loyalty & Feedback", "Reward repeat clients; collect reviews."),
            ("Reports & Analytics", "Revenue, busiest hours & top services."),
        ],
        "sectors": ["Hair salons", "Spas & wellness", "Barbershops", "Nail studios", "Beauty clinics"],
    },
]

SUITE = {
    "key": "suite", "name": "HMG Connect Suite", "icon": "🌐",
    "for": "One family of free platform generators",
    "c1": "#7c3aed", "c2": "#4f46e5", "accent": "#fde047",
    "tagline": "Ten free, no-code platforms for schools, churches, businesses & more.",
    "problem": "Every organisation needs software — but licences cost a fortune.",
    "features": [
        ("School & Church Connect", "Students, results, members, giving & events."),
        ("Business Connect", "POS, CRM, payroll, analytics & audit."),
        ("Clinic Connect", "Patients, pharmacy, labs & billing."),
        ("Hotel · Estate · Gym", "Bookings, tenants, members & more."),
        ("Logistics · Salon", "Shipments, fleet, appointments & POS."),
        ("DramaConnect", "Casting, rehearsals & production finance."),
    ],
    "sectors": ["Schools", "Churches", "Businesses", "Clinics", "Hotels", "Logistics & beauty"],
}

ALL = PRODUCTS + [SUITE]
